### ISSUE TITLE
Switch narrative from sqlite3 shell to GUI app

### ISSUE THREAD

**Issue by devbioinfoguy** [hbs-rcs/sql-novice-survey#4]
Move narrative of lessons from command line to GUI application. SWC recommends [SQLiteBrowser](https://sqlitebrowser.org/) as a cross-platform GUI.

-B

**Comment by crivera8** [comment]
Most of the narrative is in lesson 01 SELECT so I changed all the command line stuff there.  Still need to change in setup section

**Comment by devbioinfoguy** [comment]
Ooo! Let's not move too quickly on this. If we change it too drastically, we won't be able to send back to the SWC folks. Of course, if we don't care, let's move forward!!  :-)
