### ISSUE TITLE
Add Intro section prior to SELECT lesson

### ISSUE THREAD

**Issue by devbioinfoguy** [hbs-rcs/sql-novice-survey#5]
No base information nor introduction is given for the workshop. Let's talk about structured data, types of databases, etc.

-B

**Comment by crivera8** [comment]
ohhhh i just noticed that there's some brief talk about structured data, dbms etc. at the beginning of the SELECT lesson.  So I can just add my images there for now- that way you don't have to worry about adding lesson 00?

**Comment by devbioinfoguy** [comment]
Oh, what a relief. Yes, let's do that and expand it as necessary. If it starts to look rather lengthy, we might be able to hide some of the text in the magic collapsing triangles.
