### ISSUE TITLE
add R package installation instruction in setup

### ISSUE THREAD

**Issue by crivera8** [hbs-rcs/sql-novice-survey#6]
Please add R package installation instruction in setup section.  Do we need python as well?

**Comment by devbioinfoguy** [comment]
added package installation at top of R code block: https://github.com/hbs-rcs/sql-novice-survey/commit/b47530808c4dc3b33c06e03348f075b3643666ad

also updated [Setup](https://github.com/hbs-rcs/sql-novice-survey/blob/gh-pages/setup.md) document on commit https://github.com/hbs-rcs/sql-novice-survey/commit/7c50c11e70a652d42edb206cf65c8460688cfdca
